spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app10_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver